definitions:
  auth.AccessTokenRequest:
    properties:
      refreshToken:
        example: badbunybabybebe
        type: string
    required:
    - refreshToken
    type: object
  auth.LoginRequest:
    properties:
      email:
        example: mail@mail.com
        type: string
      password:
        example: Password123
        type: string
    required:
    - email
    - password
    type: object
  controllers.MessageResponse:
    properties:
      message:
        type: string
    type: object
  photo.NewPhoto:
    properties:
      caption:
        example: caption
        type: string
      photo_url:
        example: www.photo.com
        type: string
      title:
        example: title
        type: string
      user_id:
        type: integer
    required:
    - photo_url
    - title
    - user_id
    type: object
  photo.PaginationResultPhoto:
    properties:
      current:
        type: integer
      data:
        items:
          $ref: '#/definitions/photo.Photo'
        type: array
      limit:
        type: integer
      nextCursor:
        type: integer
      numPages:
        type: integer
      prevCursor:
        type: integer
      total:
        type: integer
    type: object
  photo.Photo:
    properties:
      caption:
        example: caption
        type: string
      created_at:
        example: "2021-02-24 20:19:39"
        type: string
      deletedAt:
        type: string
      id:
        example: 1099
        type: integer
      photo_url:
        example: www.photo.com
        type: string
      title:
        example: title
        type: string
      updated_at:
        example: "2021-02-24 20:19:39"
        type: string
      user_id:
        type: integer
    type: object
  user.DataSecurityAuthenticated:
    properties:
      expirationAccessDateTime:
        example: "2023-02-02T21:03:53.196419-06:00"
        type: string
      expirationRefreshDateTime:
        example: "2023-02-03T06:53:53.196419-06:00"
        type: string
      jwtAccessToken:
        example: SomeAccessToken
        type: string
      jwtRefreshToken:
        example: SomeRefreshToken
        type: string
    type: object
  user.DataUserAuthenticated:
    properties:
      email:
        example: some@mail.com
        type: string
      id:
        example: 123
        type: integer
      role:
        $ref: '#/definitions/user.Role'
      role_id:
        example: admin
        type: string
      userName:
        example: UserName
        type: string
    type: object
  user.NewUser:
    properties:
      age:
        example: 1
        type: integer
      email:
        example: mail@mail.com
        type: string
      password:
        example: Password123
        type: string
      role_id:
        type: string
      username:
        example: someUser
        type: string
    required:
    - age
    - email
    - password
    - role_id
    - username
    type: object
  user.ResponseUser:
    properties:
      age:
        example: 1
        type: integer
      createdAt:
        example: "2021-02-24 20:19:39"
        type: string
      deletedAt:
        type: string
      email:
        example: some@mail.com
        type: string
      id:
        example: 1099
        type: integer
      updatedAt:
        example: "2021-02-24 20:19:39"
        type: string
      user:
        example: BossonH
        type: string
    required:
    - age
    type: object
  user.Role:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  user.SecurityAuthenticatedUser:
    properties:
      data:
        $ref: '#/definitions/user.DataUserAuthenticated'
      security:
        $ref: '#/definitions/user.DataSecurityAuthenticated'
    type: object
info:
  contact: {}
paths:
  /auth/access-token:
    post:
      description: Auth user by email and password
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.AccessTokenRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.SecurityAuthenticatedUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      summary: GetAccessTokenByRefreshToken UserName
      tags:
      - auth
  /auth/login:
    post:
      description: Auth user by email and password
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.SecurityAuthenticatedUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      summary: Login UserName
      tags:
      - auth
  /photo:
    get:
      description: Get all Photos on the system
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/photo.PaginationResultPhoto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all Photos
      tags:
      - photo
    post:
      consumes:
      - application/json
      description: Create new photo on the system
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/photo.NewPhoto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/photo.Photo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Create New PhotoName
      tags:
      - photo
  /photo/{photo_id}:
    get:
      description: Get Photos by ID on the system
      parameters:
      - description: id of photo
        in: path
        name: photo_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get photos by ID
      tags:
      - photo
  /user:
    get:
      description: Get all Users on the system
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.ResponseUser'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all Users
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create new user on the system
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.NewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Create New UserName
      tags:
      - user
  /user/{user_id}:
    get:
      description: Get Users by ID on the system
      parameters:
      - description: id of user
        in: path
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get users by ID
      tags:
      - user
swagger: "2.0"
